#!/usr/bin/env python3
"""The consent text, from one file into three codebases (02/10).

`shared/consent/consent-text.json` holds the words of the consent screen —
the facts before the switches and the title, body, consequence of each
purpose — once, in pt-BR and en. This script writes them, verbatim, into:

- `android/app/src/main/res/values/strings_consent.xml` (pt-BR; the keys
  `ui/screens/consent/ConsentCopy.kt` maps),
- `frontend/lib/consent-text.generated.ts` (both languages),
- `backend/app/services/consent_text.py` (both languages, and the version).

Why: on 02/10 the app and the site showed different sentences under the
same text version, and a consent row that names a version must point at
exactly one text (docs/consent-texts.md). `--check` (what the backend test
runs) exits non-zero when any generated file, or the literal version in
`ConsentText.kt`, differs from the JSON.

    python3 scripts/consent_text.py          # write the three files
    python3 scripts/consent_text.py --check  # fail if anything drifted
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared" / "consent" / "consent-text.json"
ANDROID = ROOT / "android/app/src/main/res/values/strings_consent.xml"
ANDROID_VERSION = ROOT / "android/app/src/main/java/cc/tumtum/app/domain/ConsentText.kt"
FRONTEND = ROOT / "frontend/lib/consent-text.generated.ts"
BACKEND = ROOT / "backend/app/services/consent_text.py"

HEADER = "GENERATED by scripts/consent_text.py from shared/consent/consent-text.json — do not edit; edit the JSON and run the script."

# The short names the Android keys use for each purpose (consent_read_body…).
ANDROID_KEYS = {
    "terms": "terms",
    "read_heart_rate": "read",
    "keep_night": "keep",
    "crowd_stats": "crowd",
    "artist_compare": "artist",
    "improve_detection": "improve",
    "marketing": "marketing",
}
ANDROID_FIELDS = {"title": "title", "body": "body", "why": "why", "off": "stops", "locked": "locked"}


def load() -> dict:
    return json.loads(SOURCE.read_text(encoding="utf-8"))


def _android_escape(text: str) -> str:
    # Android string resources: an apostrophe or a straight quote ends the
    # string unless escaped; the texts use curly quotes, but be safe.
    return text.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"')


def android_xml(data: dict) -> str:
    pt = data["pt-BR"]
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<!-- {HEADER}",
        f"     Consent text version {data['version']}. -->",
        "<resources>",
    ]
    for key, text in pt["facts"].items():
        lines.append(f'    <string name="consent_intro_{key}">{_android_escape(text)}</string>')
    for purpose in data["purposes"]:
        short = ANDROID_KEYS[purpose]
        for field, suffix in ANDROID_FIELDS.items():
            text = pt["purposes"][purpose].get(field)
            if text is not None:
                lines.append(f'    <string name="consent_{short}_{suffix}">{_android_escape(text)}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def _ts(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def frontend_ts(data: dict) -> str:
    out = [
        f"// {HEADER}",
        "",
        f"export const CONSENT_TEXT_VERSION = {_ts(data['version'])}",
        "",
        "export type ConsentPurpose =",
    ]
    out += [f"  | {_ts(p)}" for p in data["purposes"]]
    out += [
        "",
        "/** In the order the screens show them: what the core needs first. */",
        f"export const CONSENT_PURPOSES: readonly ConsentPurpose[] = {_ts(data['purposes'])}",
        "",
        "/** The two the core loop needs, each with its own explicit yes. */",
        f"export const CORE_PURPOSES: readonly ConsentPurpose[] = {_ts(data['core'])}",
        "",
        "export interface PurposeText {",
        "  title: string",
        "  body: string",
        "  /** Why turning an optional key on is worth it, where there is a reason. */",
        "  why?: string",
        "  /** What being off means, said as the standing state: starts with Desligado. / Off. */",
        "  off: string",
        "  /** Under a key that cannot be turned off here (the Terms): how it is withdrawn. */",
        "  locked?: string",
        "}",
        "",
        "export interface ConsentText {",
        "  /** The facts before any switch, one short line each, in order. */",
        "  facts: readonly string[]",
        "  purposes: Record<ConsentPurpose, PurposeText>",
        "}",
        "",
    ]
    for lang, name in (("pt-BR", "CONSENT_TEXT_PT"), ("en", "CONSENT_TEXT_EN")):
        block = data[lang]
        out.append(f"export const {name}: ConsentText = {{")
        out.append("  facts: [")
        out += [f"    {_ts(t)}," for t in block["facts"].values()]
        out.append("  ],")
        out.append("  purposes: {")
        for purpose in data["purposes"]:
            fields = block["purposes"][purpose]
            out.append(f"    {purpose}: {{")
            for field in ("title", "body", "why", "off", "locked"):
                if field in fields:
                    out.append(f"      {field}: {_ts(fields[field])},")
            out.append("    },")
        out.append("  },")
        out.append("}")
        out.append("")
    return "\n".join(out)


def backend_py(data: dict) -> str:
    out = [
        f'"""{HEADER}',
        "",
        "The words every consent row's `text_version` points at, as the clients",
        'show them. `CONSENT_TEXT_VERSION` is imported by `services/consents.py`.',
        '"""',
        "",
        f"CONSENT_TEXT_VERSION = {_ts(data['version'])}",
        "",
        "PURPOSES = (",
        *[f"    {_ts(p)}," for p in data["purposes"]],
        ")",
        "",
        "CONSENT_TEXT: dict[str, dict] = {",
    ]
    for lang in ("pt-BR", "en"):
        block = data[lang]
        out.append(f"    {_ts(lang)}: {{")
        out.append('        "facts": [')
        out += [f"            {_ts(t)}," for t in block["facts"].values()]
        out.append("        ],")
        out.append('        "purposes": {')
        for purpose in data["purposes"]:
            fields = block["purposes"][purpose]
            out.append(f"            {_ts(purpose)}: {{")
            for field in ("title", "body", "why", "off", "locked"):
                if field in fields:
                    out.append(f"                {_ts(field)}: {_ts(fields[field])},")
            out.append("            },")
        out.append("        },")
        out.append("    },")
    out.append("}")
    return "\n".join(out) + "\n"


def outputs(data: dict) -> dict[Path, str]:
    return {ANDROID: android_xml(data), FRONTEND: frontend_ts(data), BACKEND: backend_py(data)}


def android_version_literal() -> str | None:
    m = re.search(r'const val VERSION = "([^"]+)"', ANDROID_VERSION.read_text(encoding="utf-8"))
    return m.group(1) if m else None


def drift(data: dict | None = None) -> list[str]:
    """Every way the codebases disagree with the JSON; empty when none."""
    data = data or load()
    problems = []
    for path, expected in outputs(data).items():
        if not path.exists():
            problems.append(f"{path.relative_to(ROOT)}: missing")
        elif path.read_text(encoding="utf-8") != expected:
            problems.append(f"{path.relative_to(ROOT)}: differs from the JSON (run scripts/consent_text.py)")
    literal = android_version_literal()
    if literal != data["version"]:
        problems.append(f"ConsentText.VERSION is {literal!r}, the JSON says {data['version']!r}")
    return problems


def main(argv: list[str]) -> int:
    data = load()
    if "--check" in argv:
        problems = drift(data)
        for p in problems:
            print(p, file=sys.stderr)
        return 1 if problems else 0
    for path, text in outputs(data).items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
