// GENERATED by scripts/consent_text.py from shared/consent/consent-text.json — do not edit; edit the JSON and run the script.

export const CONSENT_TEXT_VERSION = "2026-10-02.1"

export type ConsentPurpose =
  | "terms"
  | "read_heart_rate"
  | "keep_night"
  | "crowd_stats"
  | "artist_compare"
  | "improve_detection"
  | "marketing"

/** In the order the screens show them: what the core needs first. */
export const CONSENT_PURPOSES: readonly ConsentPurpose[] = ["terms", "read_heart_rate", "keep_night", "crowd_stats", "artist_compare", "improve_detection", "marketing"]

/** The two the core loop needs, each with its own explicit yes. */
export const CORE_PURPOSES: readonly ConsentPurpose[] = ["terms", "read_heart_rate"]

export interface PurposeText {
  title: string
  body: string
  /** Why turning an optional key on is worth it, where there is a reason. */
  why?: string
  /** What being off means, said as the standing state: starts with Desligado. / Off. */
  off: string
  /** Under a key that cannot be turned off here (the Terms): how it is withdrawn. */
  locked?: string
}

export interface ConsentText {
  /** The facts before any switch, one short line each, in order. */
  facts: readonly string[]
  purposes: Record<ConsentPurpose, PurposeText>
}

export const CONSENT_TEXT_PT: ConsentText = {
  facts: [
    "Batimento é dado de saúde. A lei (LGPD) trata ele como dado pessoal sensível. Por isso cada uso tem a sua chave, e nenhuma fica ligada sem você ligar.",
    "A gente só lê sua batida na janela do evento: de 30 minutos antes do começo até 30 minutos depois do fim. Fora disso, nada é lido.",
    "Com “Guardar a noite” ligado, a série de batidas fica no servidor por 7 dias depois do momento. Os momentos e os cards ficam enquanto sua conta existir e a chave estiver ligada.",
    "A TumTum não é um dispositivo médico e não interpreta saúde. Ela mostra quando seu coração subiu, nunca o que isso quer dizer.",
    "Seu dado cardíaco individual não vai para clubes, artistas, produtoras, festivais ou anunciantes. Fornecedores contratados processam dados só em nome da TumTum.",
    "Dá pra desligar qualquer chave quando quiser: no app, em Configurações → Privacidade; no site, no seu perfil.",
  ],
  purposes: {
    terms: {
      title: "Termos e Política de Privacidade",
      body: "Você leu e aceita os Termos de uso e a Política de Privacidade. Sem isso, não tem conta.",
      off: "Desligado. Sem os Termos, não tem conta.",
      locked: "Aceito. Pra retirar esse aceite, apague a conta.",
    },
    read_heart_rate: {
      title: "Ler sua batida",
      body: "Ler a batida que seu relógio ou sensor grava, só na janela do evento, e achar seus momentos. Sem isso, não tem noite.",
      off: "Desligado. Nenhuma noite nova é gravada. As que já estão aqui continuam.",
    },
    keep_night: {
      title: "Guardar a noite",
      body: "Toda noite que você gravar sobe pra sua coleção na TumTum assim que termina: a série de batidas e os momentos. Dá pra tirar qualquer noite do servidor, ou desligar esta chave, quando quiser. Sem isso, a noite fica só no seu celular.",
      why: "Pra sua noite ficar na sua coleção, entrar no feed do evento e não sumir se você trocar de celular.",
      off: "Desligado. Nenhuma noite nova sobe pra TumTum, e as que já subiram saem do servidor em até 24 horas. Elas continuam só no seu celular.",
    },
    crowd_stats: {
      title: "Entrar na galera",
      body: "Sua noite, sem seu nome, entra na conta coletiva do evento (“A galera”). Só aparece quando o evento passa de 100 noites, e sempre em faixas, tipo “25+”, nunca o número exato de pessoas.",
      off: "Desligado. Suas noites deixam de contar na galera dos eventos.",
    },
    artist_compare: {
      title: "Comparar com o artista",
      body: "Quando existir: comparar sua batida com a do artista ou do atleta que topar mostrar a dele. Ainda não existe; sua escolha fica guardada.",
      off: "Desligado. Sem comparação com artista ou atleta.",
    },
    improve_detection: {
      title: "Melhorar o detector",
      body: "Usar suas noites, sem seu nome, pra melhorar o jeito como a TumTum acha os momentos.",
      off: "Desligado. Suas noites não são usadas pra melhorar o detector.",
    },
    marketing: {
      title: "Novidades por e-mail",
      body: "Receber e-mails da TumTum sobre eventos e novidades. Sem isso, você só recebe e-mail da sua conta, como códigos e senha.",
      off: "Desligado. A gente para de mandar e-mail de novidade.",
    },
  },
}

export const CONSENT_TEXT_EN: ConsentText = {
  facts: [
    "Heart rate is health data. Brazilian law (LGPD) treats it as sensitive personal data. So each use has its own switch, and none is on unless you turn it on.",
    "We only read your heartbeat in the event's window: from 30 minutes before it starts to 30 minutes after it ends. Nothing is read outside it.",
    "With “Keep the night” on, the series of beats stays on the server for 7 days after the moment. The moments and the cards stay while your account exists and the switch is on.",
    "TumTum is not a medical device and does not interpret health. It shows when your heart rose, never what that means.",
    "Your individual heart-rate data does not go to clubs, artists, promoters, festivals or advertisers. Contracted providers process data only on TumTum's behalf.",
    "You can turn any switch off whenever you like: in the app, under Configurações → Privacidade; on the site, on your profile.",
  ],
  purposes: {
    terms: {
      title: "Terms and Privacy Policy",
      body: "You have read and accept the Terms of Use and the Privacy Policy. Without this there is no account.",
      off: "Off. Without the Terms there is no account.",
      locked: "Accepted. To withdraw it, delete the account.",
    },
    read_heart_rate: {
      title: "Read your heartbeat",
      body: "Read the heartbeat your watch or sensor records, only in the event's window, and find your moments. Without this there is no night.",
      off: "Off. No new night is recorded. The ones already here stay.",
    },
    keep_night: {
      title: "Keep the night",
      body: "Every night you record goes up to your collection on TumTum as soon as it ends: the series of beats and the moments. You can remove any night from the server, or turn this switch off, whenever you like. Without this, the night stays only on your phone.",
      why: "So your night stays in your collection, joins the event's feed and does not vanish if you change phones.",
      off: "Off. No new night is uploaded to TumTum, and the ones already uploaded leave the server within 24 hours. They stay only on your phone.",
    },
    crowd_stats: {
      title: "Join the crowd",
      body: "Your night joins, without your name, the event's collective count (“A galera”). It only appears once the event passes 100 nights, and always in bands, like “25+”, never the exact number of people.",
      off: "Off. Your nights no longer count in the events' crowd.",
    },
    artist_compare: {
      title: "Compare with the artist",
      body: "When it exists: compare your heartbeat with that of the artist or athlete who agrees to show theirs. It does not exist yet; your choice is kept.",
      off: "Off. No comparison with an artist or athlete.",
    },
    improve_detection: {
      title: "Improve the detector",
      body: "Use your nights, without your name, to improve how TumTum finds the moments.",
      off: "Off. Your nights are not used to improve the detector.",
    },
    marketing: {
      title: "News by e-mail",
      body: "Get e-mails from TumTum about events and news. Without this, you only get account e-mails, like codes and passwords.",
      off: "Off. We stop sending news e-mails.",
    },
  },
}
